### ISSUE TITLE
Integration suite does not compile on main: three specs call a helper Integration.Support no longer exports

### ISSUE THREAD

**Issue by jordan-stor-z** [v12-Industry/typeio_2#420]
## Summary

The `integration` test-suite does not compile on `main`. Three specs import `seedProjectWithRootNode` from `Integration.Support`, which exports `seedProject` instead.

```
test-integration/Domain/Project/Responder/Ui/ProjectManage/Node/LabelSpec.hs:30:5: error:
    Module ‘Integration.Support’ does not export ‘seedProjectWithRootNode’
```

## Where

`test-integration/Integration/Support.hs` exports and defines `seedProject :: TestApp -> IO (Key M.Project)`. These three still call `seedProjectWithRootNode ta` and destructure a tuple from it:

- `test-integration/Domain/Project/Responder/Ui/ProjectManage/Node/LabelSpec.hs`
- `test-integration/Domain/Project/Responder/Ui/ProjectManage/Node/RefreshSpec.hs`
- `test-integration/Domain/Project/Visualization/Rootless/ResponderSpec.hs`

So the fix is not a pure rename: the old helper returned the project key *and* its root node, and the callers use both.

## How it got past CI

`integration-test.yml` runs on pull requests, and the merge queue re-runs `test` (unit) against the merge group rather than `integration`. Two PRs can each be green on their own — one renaming the helper, one adding a spec that uses the old name — and still produce a `main` where the suite does not build, because nothing ever compiles the combination until the next PR rebases onto it.

## Effect

Every PR branched from or rebased onto current `main` fails the required `integration` check for a reason unrelated to its own diff. Found while rebasing #414.

## Worth considering

Whether the merge queue should run `integration` against the merge group as well, since this class of semantic conflict is exactly what a merge queue exists to catch.
